### ISSUE TITLE
为啥这个npm i的时候一直卡在一个地方不动

### ISSUE THREAD

**Issue by OnlyForYouYaner** [seiwhale/vue-cms#2]

**Comment by seiwhale** [comment]
可以尝试使用 cnpm 或者 yarn

```
npm install --registry=https://registry.npm.taobao.org
```

**Comment by OnlyForYouYaner** [comment]
ok，我解决啦




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"鲸落"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月2日(星期四) 下午2:51
收件人:&nbsp;"seiwhale/vue-cms"<vue-cms@noreply.github.com&gt;;
抄送:&nbsp;"浮华春秋只为你??"<1738796124@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [seiwhale/vue-cms] 为啥这个npm i的时候一直卡在一个地方不动 (#2)





 
可以尝试使用 cnpm 或者 yarn
 npm install --registry=https://registry.npm.taobao.org
